In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob
import os
import json
from datetime import datetime

In [2]:
df1=pd.read_csv('file1.csv')
df2=pd.read_csv('file2.csv')

In [3]:
df1

,Unnamed: 0,Device_ID,Event_ID,Event_start_time,Tags,Free_text,Name_of_cat,Weight_of_cat,Tare_weight,min_sum,max_sum,mean_sum,std_sum,duration_of_event,max_10_dev,max_10_dur,Total_Tare_weight,hour_day
0,0,VA00000000000022,RXZlbnRJbmZvcm1hdGlvbjplZTIwZDI4MC1iMTNkLTQwYj...,2020-10-02 16:14:13,"['cat in box', 'defecation']",NaN,Sparkler,4429,"[4882, 2049, 1642, 3099]",11699.0,17020.0,14796.140873,2032.140749,201.574933,11700.0,55.375,11672,16.2
1,1,VA00000000000037,RXZlbnRJbmZvcm1hdGlvbjo0MzdlNTU1MS1hODQ2LTQyMW...,2021-10-12 14:10:23,"['urination', 'cat in box']","14:20:24\t14:11:27\tConfirmed activity, cat in...",Negan,4634,"[487, 2189, 1157, 4353]",8166.0,14423.0,10534.855519,2328.319056,123.174941,8180.0,58.950,8186,14.2
2,2,VA00000000000037,RXZlbnRJbmZvcm1hdGlvbjo0NDM5M2M2ZS1iYTQ5LTRhMD...,2021-10-15 15:31:15,"['non_elimination', 'cat in box']","15:31:15\t15:31:19\tConfirmed activity, cat in...",Negan,4920,"[426, 1997, 737, 4750]",7911.0,13268.0,8123.100870,936.702194,63.174944,7910.0,42.900,7910,15.5
3,3,VA00000000000037,RXZlbnRJbmZvcm1hdGlvbjo0NjgwYjJhMy00MjQzLTQwOD...,2021-01-11 13:19:24,"['cat in box', 'defecation']","13:19:10\t13:21:25\tConfirmed activity, cat in...",Negan,5510,"[1752, -158, 1626, 4359]",7554.0,14302.0,11161.678697,2634.601155,170.374946,7600.0,26.950,7579,13.3
4,4,VA00000000000037,RXZlbnRJbmZvcm1hdGlvbjo0NjhiZGY1Mi0wNzMyLTQzOD...,2021-01-13 13:01:52,"['cat in box', 'defecation']","13:01:45\t13:04:44\tConfirmed activity, cat in...",Negan,5523,"[1584, -948, 3099, 3569]",7332.0,13929.0,11382.558798,2434.302037,229.574936,7340.0,34.800,7304,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12058,12058,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjplOTY1YzllOC01YWU1LTRmYj...,2021-08-24 01:36:18,"['urination', 'cat in box']","1:36:18\t1:37:07\tConfirmed activity, cat in t...",Sparkler,4116,"[2340, 868, 2150, 1626]",6040.0,13033.0,10371.323902,1583.759646,59.125914,7030.0,7.125,6984,1.6
12059,12059,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmNDMxM2YwNi1hNzk0LTQxMG...,2021-04-26 06:29:01,"['cat in box', 'non_elimination']",NaN,Sparkler,4604,"[3577, 400, 2043, 1747]",7711.0,13016.0,8288.571913,1390.112340,132.144766,7750.0,53.425,7767,6.5
12060,12060,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmYjQ3YzJkZi03ODY3LTQ3Zm...,2021-04-27 03:47:55,"['urination', 'cat in box']",NaN,Sparkler,4416,"[4313, -14729, 1754, 1697]",7579.0,12509.0,10080.843208,2186.401587,137.820918,7600.0,40.600,-6965,3.8
12061,12061,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmYTY2MzA0OC1kNjQ1LTQ5OD...,2021-09-02 01:15:57,"['cat in box', 'defecation']","1:15:53\t1:19:07\tConfirmed activity, cat in t...",Sparkler,4386,"[3702, -893, 1561, 1940]",6332.0,11965.0,10486.627554,976.953183,205.381823,10710.0,23.225,6310,1.2
12062,12062,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmZTc0ZmZlNS1mZjdhLTRlYj...,2021-10-03 14:45:43,"['cat in box', 'urination']","14:45:43\t14:47:08\tConfirmed activity, cat in...",Sparkler,4510,"[2867, -689, 2402, 3441]",8037.0,13572.0,12036.476103,1415.763551,95.103066,8040.0,9.225,8021,14.8

In [4]:

df1.drop(['Unnamed: 0','Free_text','Tags','Name_of_cat','Weight_of_cat','min_sum','max_sum','mean_sum','std_sum','duration_of_event'],axis=1,inplace=True)

In [5]:
df2

,Unnamed: 0,Device_ID,Event_ID,Event_start_time,Tags,Free_text,Name_of_cat,Weight_of_cat,Tare_weight,min_sum,max_sum,mean_sum,std_sum,duration_of_event,count_max_shift,count_min_shift
0,0,VA00000000000017,RXZlbnRJbmZvcm1hdGlvbjo0OWQ4M2I3MS1kNDZmLTRiYj...,2020-09-05T10:56:11-05:00,"['urination', 'cat in box']",NaN,Ryan,6589,NaN,7982,16035,10112.065130,2961.452803,151.974936,53,0
1,1,VA00000000000017,RXZlbnRJbmZvcm1hdGlvbjo0YmI3ZDc5YS0wNzMwLTQ0MT...,2020-07-18T14:41:37-05:00,"['cat in box', 'synapse_labeled', 'urination']","14:42:15\t14:43:09\tConfirmed activity, cat in...",Ryan,6935,NaN,6796,14962,10049.854460,3453.251838,111.975000,34,0
2,2,VA00000000000017,RXZlbnRJbmZvcm1hdGlvbjo0ZTBhMDVhOC0wZmI2LTQ2MG...,2020-09-03T15:43:43-05:00,"['cat in box', 'urination']",NaN,Ryan,5139,NaN,8739,15311,11050.497560,2572.058837,102.374944,5,3
3,3,VA00000000000017,RXZlbnRJbmZvcm1hdGlvbjo1NGEwMTg2My01NDhjLTRhYT...,2020-09-01T12:02:05-05:00,"['non_elimination', 'cat in box']",NaN,Ryan,6983,NaN,8786,16092,9855.522214,2384.826901,66.374940,1,7
4,4,VA00000000000017,RXZlbnRJbmZvcm1hdGlvbjo1YzQwMzE4MS1lNzhkLTQ3Nz...,2020-08-08T06:47:11-05:00,"['cat in box', 'synapse_labeled', 'urination']","6:47:16\t6:48:59\tConfirmed activity, cat in t...",Ryan,7017,NaN,4760,12523,8927.666566,3379.644350,82.375000,22,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13070,13070,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjplOTY1YzllOC01YWU1LTRmYj...,2021-08-24T01:36:18-05:00,"['urination', 'cat in box']","1:36:18\t1:37:07\tConfirmed activity, cat in t...",Sparkler,4116,"[2340, 868, 2150, 1626]",6040,13033,10371.323900,1583.759646,59.125914,36,10
13071,13071,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmNDMxM2YwNi1hNzk0LTQxMG...,2021-04-26T06:29:01-05:00,"['cat in box', 'non_elimination']",NaN,Sparkler,4604,"[3577, 400, 2043, 1747]",7711,13016,8288.571913,1390.112340,132.144766,6,18
13072,13072,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmYjQ3YzJkZi03ODY3LTQ3Zm...,2021-04-27T03:47:55-05:00,"['urination', 'cat in box']",NaN,Sparkler,4416,"[4313, -14729, 1754, 1697]",7579,12509,10080.843210,2186.401587,137.820918,0,69
13073,13073,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmYTY2MzA0OC1kNjQ1LTQ5OD...,2021-09-02T01:15:57-05:00,"['cat in box', 'defecation']","1:15:53\t1:19:07\tConfirmed activity, cat in t...",Sparkler,4386,"[3702, -893, 1561, 1940]",6332,11965,10486.627550,976.953183,205.381823,46,9
13074,13074,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmZTc0ZmZlNS1mZjdhLTRlYj...,2021-10-03T14:45:43-05:00,"['cat in box', 'urination']","14:45:43\t14:47:08\tConfirmed activity, cat in...",Sparkler,4510,"[2867, -689, 2402, 3441]",8037,13572,12036.476100,1415.763551,95.103066,104,0

In [6]:

df2.drop(['Unnamed: 0','Device_ID','Event_start_time','Free_text','Tare_weight'],axis=1,inplace=True)

In [7]:
df=pd.merge(df1,df2, how ='left', on ='Event_ID')

In [20]:
df

,Device_ID,Event_ID,Event_start_time,Tare_weight,max_10_dev,max_10_dur,Total_Tare_weight,hour_day,Tags,Name_of_cat,...,std_sum,duration_of_event,count_max_shift,count_min_shift,ratio_10_weight,ratio_min_weight,ratio_min_10_weight,cat_in_box,month,elimination
0,VA00000000000022,RXZlbnRJbmZvcm1hdGlvbjplZTIwZDI4MC1iMTNkLTQwYj...,2020-10-02 16:14:13,"[4882, 2049, 1642, 3099]",11700.0,0.274712,11672,16.2,"['cat in box', 'defecation']",Sparkler,...,2032.140749,201.574933,0.000000,0.034727,-0.006322,-0.006096,0.000226,1,10,1
1,VA00000000000037,RXZlbnRJbmZvcm1hdGlvbjo0MzdlNTU1MS1hODQ2LTQyMW...,2021-10-12 14:10:23,"[487, 2189, 1157, 4353]",8180.0,0.478588,8186,14.2,"['urination', 'cat in box']",Negan,...,2328.319056,123.174941,0.251675,0.194845,0.001295,0.004316,0.003021,1,10,1
2,VA00000000000037,RXZlbnRJbmZvcm1hdGlvbjo0NDM5M2M2ZS1iYTQ5LTRhMD...,2021-10-15 15:31:15,"[426, 1997, 737, 4750]",7910.0,0.679067,7910,15.5,"['non_elimination', 'cat in box']",Negan,...,936.702194,63.174944,0.031658,0.047487,0.000000,-0.000203,-0.000203,1,10,0
3,VA00000000000037,RXZlbnRJbmZvcm1hdGlvbjo0NjgwYjJhMy00MjQzLTQwOD...,2021-01-11 13:19:24,"[1752, -158, 1626, 4359]",7600.0,0.158181,7579,13.3,"['cat in box', 'defecation']",Negan,...,2634.601155,170.374946,0.058694,0.164343,-0.003811,0.004537,0.008348,1,1,1
4,VA00000000000037,RXZlbnRJbmZvcm1hdGlvbjo0NjhiZGY1Mi0wNzMyLTQzOD...,2021-01-13 13:01:52,"[1584, -948, 3099, 3569]",7340.0,0.151584,7304,13.0,"['cat in box', 'defecation']",Negan,...,2434.302037,229.574936,0.361538,0.021779,-0.006518,-0.005070,0.001448,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12058,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjplOTY1YzllOC01YWU1LTRmYj...,2021-08-24 01:36:18,"[2340, 868, 2150, 1626]",7030.0,0.120506,6984,1.6,"['urination', 'cat in box']",Sparkler,...,1583.759646,59.125914,0.608870,0.169131,-0.011176,0.229349,0.240525,1,8,1
12059,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmNDMxM2YwNi1hNzk0LTQxMG...,2021-04-26 06:29:01,"[3577, 400, 2043, 1747]",7750.0,0.404291,7767,6.5,"['cat in box', 'non_elimination']",Sparkler,...,1390.112340,132.144766,0.045405,0.136214,0.003692,0.012163,0.008471,1,4,0
12060,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmYjQ3YzJkZi03ODY3LTQ3Zm...,2021-04-27 03:47:55,"[4313, -14729, 1754, 1697]",7600.0,0.294585,-6965,3.8,"['urination', 'cat in box']",Sparkler,...,2186.401587,137.820918,0.000000,0.500650,-3.298234,-3.293478,0.004755,1,4,1
12061,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmYTY2MzA0OC1kNjQ1LTQ5OD...,2021-09-02 01:15:57,"[3702, -893, 1561, 1940]",10710.0,0.113082,6310,1.2,"['cat in box', 'defecation']",Sparkler,...,976.953183,205.381823,0.223973,0.043821,-1.003192,-0.005016,0.998176,1,9,1
12062,VB00000000000192,RXZlbnRJbmZvcm1hdGlvbjpmZTc0ZmZlNS1mZjdhLTRlYj...,2021-10-03 14:45:43,"[2867, -689, 2402, 3441]",8040.0,0.097000,8021,14.8,"['cat in box', 'urination']",Sparkler,...,1415.763551,95.103066,1.093550,0.000000,-0.004213,-0.003548,0.000665,1,10,1

In [9]:
for i in range(df.shape[0]):
    df['Event_start_time'][i]=df['Event_start_time'][i][2:]
    df['Event_start_time'][i]=df['Event_start_time'][i].replace('-','/')
    df['Event_start_time'][i]=df['Event_start_time'][i].replace('T',' ')
for i in range(df.shape[0]):
        datetime_str =df['Event_start_time'][i] 
        df['Event_start_time'][i] = datetime.strptime(datetime_str, '%y/%m/%d %H:%M:%S')

C:\Users\chandra.gorripat\AppData\Local\Temp\ipykernel_31908\3908000891.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Event_start_time'][i]=df['Event_start_time'][i][2:]
C:\Users\chandra.gorripat\AppData\Local\Temp\ipykernel_31908\3908000891.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Event_start_time'][i]=df['Event_start_time'][i].replace('-','/')
C:\Users\chandra.gorripat\AppData\Local\Temp\ipykernel_31908\3908000891.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Event_start_time'][i]=df['Event_start_time'][i].replace('T',' ')
C:\Users\chandra.gorripat\AppData\Local\Temp\ipykernel_31908\3908000891.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Event_start_time'][i] = datetime.strptime(datetime_str, '%y/%m/%d %H:%M:%S')

In [10]:
df['ratio_10_weight']=(df['Total_Tare_weight']-df['max_10_dev'])/df['Weight_of_cat']
df['ratio_min_weight']=(df['Total_Tare_weight']-df['min_sum'])/df['Weight_of_cat']
df['ratio_min_10_weight']=(df['max_10_dev']-df['min_sum'])/df['Weight_of_cat']

In [11]:
df['cat_in_box']=0
for i in range(df.shape[0]):
    if 'cat in box' in df['Tags'][i]:
        df['cat_in_box'][i]=1

C:\Users\chandra.gorripat\AppData\Local\Temp\ipykernel_31908\3781023204.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cat_in_box'][i]=1

In [12]:
df[df['Weight_of_cat']==0]

,Device_ID,Event_ID,Event_start_time,Tare_weight,max_10_dev,max_10_dur,Total_Tare_weight,hour_day,Tags,Name_of_cat,...,max_sum,mean_sum,std_sum,duration_of_event,count_max_shift,count_min_shift,ratio_10_weight,ratio_min_weight,ratio_min_10_weight,cat_in_box
2823,VA00000000000064,RXZlbnRJbmZvcm1hdGlvbjo0NGFkODI5NS03M2Y0LTQ4ZW...,2020-10-23 19:21:21,"[1322, 888, 2740, 846]",5750.0,12.675,5796,19.3,['non_elimination'],NaN,...,6341,5538.640752,413.458847,98.374950,0,466,inf,inf,inf,0
2950,VA00000000000065,RXZlbnRJbmZvcm1hdGlvbjpjYTRjMDZiMi03Y2VjLTQ5MW...,2020-10-27 19:54:30,"[5303, 1412, 2114, 4572]",13350.0,31.025,13401,19.9,['non_elimination'],NaN,...,17590,12920.044510,686.996062,216.774934,178,90,inf,inf,inf,0
10997,VB00000000000186,RXZlbnRJbmZvcm1hdGlvbjo5MTQxYzVhMi1lMDJmLTQyYT...,2021-04-12 20:17:45,"[360, 5145, 19701, 4107]",11480.0,0.175,29313,20.3,"['cat in box', 'non_elimination']",Spark,...,11639,10875.243750,911.740169,3.983949,7,0,inf,inf,inf,1

In [13]:
df['max_10_dur']=df['max_10_dur']/df['duration_of_event']
df['count_max_shift']=df['count_max_shift']/df['duration_of_event']
df['count_min_shift']=df['count_min_shift']/df['duration_of_event']

In [14]:

df['month']=0
for i in range(df.shape[0]):
    df['month'][i]=df['Event_start_time'][i].month

C:\Users\chandra.gorripat\AppData\Local\Temp\ipykernel_31908\2343691363.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'][i]=df['Event_start_time'][i].month

In [15]:
df1=df

In [16]:
df['elimination']=0
for i in range(df.shape[0]):
    if 'urination' in df['Tags'][i]:
        df['elimination'][i]=1
    if 'defecation' in df['Tags'][i]:
        df['elimination'][i]=1

C:\Users\chandra.gorripat\AppData\Local\Temp\ipykernel_31908\701011203.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['elimination'][i]=1
C:\Users\chandra.gorripat\AppData\Local\Temp\ipykernel_31908\701011203.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['elimination'][i]=1

In [17]:
df.drop(index=2823,inplace=True)
df.drop(index=2950,inplace=True)
df.drop(index=10997,inplace=True)

In [18]:
df.to_csv('final.csv')

In [19]:
df.corr()

,max_10_dev,max_10_dur,Total_Tare_weight,hour_day,Weight_of_cat,min_sum,max_sum,mean_sum,std_sum,duration_of_event,count_max_shift,count_min_shift,ratio_10_weight,ratio_min_weight,ratio_min_10_weight,cat_in_box,month,elimination
max_10_dev,1.000000,-0.180951,0.640170,-0.028398,-0.026812,0.895224,0.811453,0.931982,-0.167743,0.016929,-0.031798,0.011255,-0.107255,0.062786,0.229136,0.011472,0.137932,0.129611
max_10_dur,-0.180951,1.000000,-0.002670,0.049687,-0.111001,-0.006715,-0.027279,-0.239429,-0.077626,-0.260496,-0.117329,-0.098148,0.157505,0.012335,-0.181489,0.008554,-0.135207,-0.318129
Total_Tare_weight,0.640170,-0.002670,1.000000,-0.023407,-0.064686,0.695199,0.624486,0.666727,-0.062094,-0.002242,-0.035941,-0.020423,0.668834,0.592041,0.029480,0.002997,0.050286,0.022107
hour_day,-0.028398,0.049687,-0.023407,1.000000,-0.017809,-0.032549,-0.033775,-0.039819,-0.000829,-0.079401,-0.005018,-0.002843,-0.006977,0.000325,0.009332,-0.017063,0.001985,0.014385
Weight_of_cat,-0.026812,-0.111001,-0.064686,-0.017809,1.000000,-0.040263,0.209455,0.084980,0.742622,0.054035,0.068933,0.050203,-0.009499,-0.095188,-0.129088,0.065837,-0.027166,0.029913
min_sum,0.895224,-0.006715,0.695199,-0.032549,-0.040263,1.000000,0.874523,0.943415,-0.025290,0.021645,-0.044398,-0.002914,0.053950,0.040893,-0.007797,0.014609,0.019119,0.073465
max_sum,0.811453,-0.027279,0.624486,-0.033775,0.209455,0.874523,1.000000,0.885714,0.161213,0.065093,-0.025367,0.012891,0.052002,0.064075,0.029046,0.021189,0.008375,0.065829
mean_sum,0.931982,-0.239429,0.666727,-0.039819,0.084980,0.943415,0.885714,1.000000,0.048877,0.100056,-0.015669,0.018481,-0.008061,0.052517,0.088093,0.021145,0.082334,0.156375
std_sum,-0.167743,-0.077626,-0.062094,-0.000829,0.742622,-0.025290,0.161213,0.048877,1.000000,0.117751,0.064040,0.034261,0.107427,-0.074647,-0.246940,0.045085,-0.186401,0.172694
duration_of_event,0.016929,-0.260496,-0.002242,-0.079401,0.054035,0.021645,0.065093,0.100056,0.117751,1.000000,0.023948,0.017435,-0.015156,-0.005500,0.011069,-0.006806,-0.230460,0.383080
count_max_shift,-0.031798,-0.117329,-0.035941,-0.005018,0.068933,-0.044398,-0.025367,-0.015669,0.064040,0.023948,1.000000,0.014883,-0.017538,-0.007593,0.010988,-0.002527,0.014323,0.031638
count_min_shift,0.011255,-0.098148,-0.020423,-0.002843,0.050203,-0.002914,0.012891,0.018481,0.034261,0.017435,0.014883,1.000000,-0.029398,-0.012335,0.018999,-0.013625,0.008715,0.016436
ratio_10_weight,-0.107255,0.157505,0.668834,-0.006977,-0.009499,0.053950,0.052002,-0.008061,0.107427,-0.015156,-0.017538,-0.029398,1.000000,0.746349,-0.161777,-0.008405,-0.066724,-0.085094
ratio_min_weight,0.062786,0.012335,0.592041,0.000325,-0.095188,0.040893,0.064075,0.052517,-0.074647,-0.005500,-0.007593,-0.012335,0.746349,1.000000,0.536046,-0.171572,0.034469,-0.041614
ratio_min_10_weight,0.229136,-0.181489,0.029480,0.009332,-0.129088,-0.007797,0.029046,0.088093,-0.246940,0.011069,0.010988,0.018999,-0.161777,0.536046,1.000000,-0.243732,0.135740,0.046231
cat_in_box,0.011472,0.008554,0.002997,-0.017063,0.065837,0.014609,0.021189,0.021145,0.045085,-0.006806,-0.002527,-0.013625,-0.008405,-0.171572,-0.243732,1.000000,-0.021839,0.030924
month,0.137932,-0.135207,0.050286,0.001985,-0.027166,0.019119,0.008375,0.082334,-0.186401,-0.230460,0.014323,0.008715,-0.066724,0.034469,0.135740,-0.021839,1.000000,-0.115401
elimination,0.129611,-0.318129,0.022107,0.014385,0.029913,0.073465,0.065829,0.156375,0.172694,0.383080,0.031638,0.016436,-0.085094,-0.041614,0.046231,0.030924,-0.115401,1.000000